version: '2'

services:

  # app
  app:
    build: 
      context: .
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - /var/www/storage
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # web
  web:
    build: 
      context: .
      dockerfile: web.dockerfile
    ports:
      - 80:80

  # The Database
  database:
    build: 
      context: .
      dockerfile: db.dockerfile
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata: